// BSD 3-Clause License
//
// Copyright (c) 2022-2026, Woven by Toyota. All rights reserved.
//
// Redistribution and use in source and binary forms, with or without
// modification, are permitted provided that the following conditions are met:
//
// * Redistributions of source code must retain the above copyright notice, this
//   list of conditions and the following disclaimer.
//
// * Redistributions in binary form must reproduce the above copyright notice,
//   this list of conditions and the following disclaimer in the documentation
//   and/or other materials provided with the distribution.
//
// * Neither the name of the copyright holder nor the names of its
//   contributors may be used to endorse or promote products derived from
//   this software without specific prior written permission.
//
// THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
// AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
// IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
// DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE
// FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
// DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
// SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
// CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
// OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
// OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
#pragma once

#include <unordered_map>

#include "maliput/common/maliput_hash.h"

namespace maliput {
namespace api {

/// Defines shared traffic control device semantics.
///
/// This enum is the single source of truth for both traffic sign and road
/// marking semantic types.
enum class TrafficControlDeviceType {
  kNone = 0,
  kOther,
  kStop,
  kYield,
  kSpeedLimit,
  kNoEntry,
  kOneWay,
  kPedestrianCrossing,
  kNoLeftTurn,
  kNoRightTurn,
  kNoUTurn,
  kSchoolZone,
  kConstruction,
  kRailroadCrossing,
  kNoOvertaking,
  kAllWay,
  kNoUTurnLeft,
  kNoUTurnRight,
  kStopLine,
  kCrosswalk,
  kDangerSpot,
  kZebraCrossing,
  kFlight,
  kCattle,
  kHorseRiders,
  kAmphibians,
  kFallingRocks,
  kSnowOrIce,
  kLooseGravel,
  kWaterside,
  kClearance,
  kMovableBridge,
  kRightBeforeLeftNextIntersection,
  kTurnLeft,
  kTurnRight,
  kDoubleTurnLeft,
  kDoubleTurnRight,
  kHillDownwards,
  kHillUpwards,
  kUnevenRoad,
  kRoadSlipperyWetOrDirty,
  kSideWinds,
  kRoadNarrowing,
  kRoadNarrowingRight,
  kRoadNarrowingLeft,
  kRoadWorks,
  kTrafficQueues,
  kTwoWayTraffic,
  kAttentionTrafficLight,
  kPedestrians,
  kChildrenCrossing,
  kCycleRoute,
  kDeerCrossing,
  kUngatedLevelCrossing,
  kLevelCrossingMarker,
  kRailwayTrafficPriority,
  kGiveWay,
  kPriorityToOppositeDirection,
  kPriorityToOppositeDirectionUpsideDown,
  kPrescribedLeftTurn,
  kPrescribedRightTurn,
  kPrescribedStraight,
  kPrescribedRightWay,
  kPrescribedLeftWay,
  kPrescribedRightTurnAndStraight,
  kPrescribedLeftTurnAndStraight,
  kPrescribedLeftTurnAndRightTurn,
  kPrescribedLeftTurnRightTurnAndStraight,
  kRoundabout,
  kOnewayLeft,
  kOnewayRight,
  kPassLeft,
  kPassRight,
  kSideLaneOpenForTraffic,
  kSideLaneClosedForTraffic,
  kSideLaneClosingForTraffic,
  kBusStop,
  kTaxiStand,
  kBicyclesOnly,
  kHorseRidersOnly,
  kPedestriansOnly,
  kBicyclesPedestriansSharedOnly,
  kBicyclesPedestriansSeparatedLeftOnly,
  kBicyclesPedestriansSeparatedRightOnly,
  kPedestrianZoneBegin,
  kPedestrianZoneEnd,
  kBicycleRoadBegin,
  kBicycleRoadEnd,
  kBusLane,
  kBusLaneBegin,
  kBusLaneEnd,
  kAllProhibited,
  kMotorizedMultitrackProhibited,
  kTrucksProhibited,
  kBicyclesProhibited,
  kMotorcyclesProhibited,
  kMopedsProhibited,
  kHorseRidersProhibited,
  kHorseCarriagesProhibited,
  kCattleProhibited,
  kBusesProhibited,
  kCarsProhibited,
  kCarsTrailersProhibited,
  kTrucksTrailersProhibited,
  kTractorsProhibited,
  kPedestriansProhibited,
  kMotorVehiclesProhibited,
  kHazardousGoodsVehiclesProhibited,
  kOverWeightVehiclesProhibited,
  kVehiclesAxleOverWeightProhibited,
  kVehiclesExcessWidthProhibited,
  kVehiclesExcessHeightProhibited,
  kVehiclesExcessLengthProhibited,
  kDoNotEnter,
  kSnowChainsRequired,
  kWaterPollutantVehiclesProhibited,
  kEnvironmentalZoneBegin,
  kEnvironmentalZoneEnd,
  kPrescribedUTurnLeft,
  kPrescribedUTurnRight,
  kMinimumDistanceForTrucks,
  kSpeedLimitBegin,
  kSpeedLimitZoneBegin,
  kSpeedLimitZoneEnd,
  kMinimumSpeedBegin,
  kOvertakingBanBegin,
  kOvertakingBanForTrucksBegin,
  kSpeedLimitEnd,
  kMinimumSpeedEnd,
  kOvertakingBanEnd,
  kOvertakingBanForTrucksEnd,
  kAllRestrictionsEnd,
  kNoStopping,
  kNoParking,
  kNoParkingZoneBegin,
  kNoParkingZoneEnd,
  kRightOfWayNextIntersection,
  kRightOfWayBegin,
  kRightOfWayEnd,
  kPriorityOverOppositeDirection,
  kPriorityOverOppositeDirectionUpsideDown,
  kTownBegin,
  kTownEnd,
  kCarParking,
  kCarParkingZoneBegin,
  kCarParkingZoneEnd,
  kSidewalkHalfParkingLeft,
  kSidewalkHalfParkingRight,
  kSidewalkParkingLeft,
  kSidewalkParkingRight,
  kSidewalkPerpendicularHalfParkingLeft,
  kSidewalkPerpendicularHalfParkingRight,
  kSidewalkPerpendicularParkingLeft,
  kSidewalkPerpendicularParkingRight,
  kLivingStreetBegin,
  kLivingStreetEnd,
  kTunnel,
  kEmergencyStoppingLeft,
  kEmergencyStoppingRight,
  kHighwayBegin,
  kHighwayEnd,
  kExpresswayBegin,
  kExpresswayEnd,
  kNamedHighwayExit,
  kNamedExpresswayExit,
  kNamedRoadExit,
  kHighwayExit,
  kExpresswayExit,
  kOnewayStreet,
  kCrossingGuards,
  kDeadend,
  kDeadendExcludingDesignatedActors,
  kFirstAidStation,
  kPoliceStation,
  kTelephone,
  kFillingStation,
  kHotel,
  kInn,
  kKiosk,
  kToilet,
  kChapel,
  kTouristInfo,
  kRepairService,
  kPedestrianUnderpass,
  kPedestrianBridge,
  kCamperPlace,
  kAdvisorySpeedLimitBegin,
  kAdvisorySpeedLimitEnd,
  kPlaceName,
  kTouristAttraction,
  kTouristRoute,
  kTouristArea,
  kShoulderNotPassableMotorVehicles,
  kShoulderUnsafeTrucksTractors,
  kTollBegin,
  kTollEnd,
  kTollRoad,
  kCustoms,
  kInternationalBorderInfo,
  kStreetlightRedBand,
  kFederalHighwayRouteNumber,
  kHighwayRouteNumber,
  kHighwayInterchangeNumber,
  kEuropeanRouteNumber,
  kFederalHighwayDirectionLeft,
  kFederalHighwayDirectionRight,
  kPrimaryRoadDirectionLeft,
  kPrimaryRoadDirectionRight,
  kSecondaryRoadDirectionLeft,
  kSecondaryRoadDirectionRight,
  kDirectionDesignatedActorsLeft,
  kDirectionDesignatedActorsRight,
  kRoutingDesignatedActors,
  kDirectionToHighwayLeft,
  kDirectionToHighwayRight,
  kDirectionToLocalDestinationLeft,
  kDirectionToLocalDestinationRight,
  kConsolidatedDirections,
  kStreetName,
  kDirectionPreannouncement,
  kDirectionPreannouncementLaneConfig,
  kDirectionPreannouncementHighwayEntries,
  kHighwayAnnouncement,
  kOtherRoadAnnouncement,
  kHighwayAnnouncementTruckStop,
  kHighwayPreannouncementDirections,
  kPoleExit,
  kHighwayDistanceBoard,
  kDetourLeft,
  kDetourRight,
  kNumberedDetour,
  kDetourBegin,
  kDetourEnd,
  kDetourRoutingBoard,
  kOptionalDetour,
  kOptionalDetourRouting,
  kRouteRecommendation,
  kRouteRecommendationEnd,
  kAnnounceLaneTransitionLeft,
  kAnnounceLaneTransitionRight,
  kAnnounceRightLaneEnd,
  kAnnounceLeftLaneEnd,
  kAnnounceRightLaneBegin,
  kAnnounceLeftLaneBegin,
  kAnnounceLaneConsolidation,
  kDetourCityBlock,
  kGate,
  kPoleWarning,
  kTrafficCone,
  kMobileLaneClosure,
  kReflectorPost,
  kDirectionalBoardWarning,
  kGuidingPlate,
  kGuidingPlateWedges,
  kParkingHazard,
  kTrafficLightGreenArrow,
  kText,
  kSpace,
  kTime,
  kArrow,
  kConstrainedTo,
  kExcept,
  kValidForDistance,
  kPriorityRoadBottomLeftFourWay,
  kPriorityRoadTopLeftFourWay,
  kPriorityRoadBottomLeftThreeWayStraight,
  kPriorityRoadBottomLeftThreeWaySideways,
  kPriorityRoadTopLeftThreeWayStraight,
  kPriorityRoadBottomRightFourWay,
  kPriorityRoadTopRightFourWay,
  kPriorityRoadBottomRightThreeWayStraight,
  kPriorityRoadBottomRightThreeWaySideway,
  kPriorityRoadTopRightThreeWayStraight,
  kValidInDistance,
  kStopIn,
  kLeftArrow,
  kLeftBendArrow,
  kRightArrow,
  kRightBendArrow,
  kAccident,
  kSnow,
  kFog,
  kRollingHighwayInformation,
  kServices,
  kTimeRange,
  kParkingDiscTimeRestriction,
  kWeight,
  kWet,
  kParkingConstraint,
  kNoWaitingSideStripes,
  kRain,
  kSnowRain,
  kNight,
  kStop4Way,
  kTruck,
  kTractorsMayBePassed,
  kHazardous,
  kTrailer,
  kZone,
  kMotorcycle,
  kMotorcycleAllowed,
  kCar,
  kParkingSpace,
  kEmergencyLane,
  kDoNotStop,
  kRailRoad,
  kArrowTurnRight,
  kArrowTurnLeft,
  kArrowForwardTurnRight,
  kArrowForwardTurnLeft,
  kArrowForward,
  kArrowForwardTurnRightTurnLeft,
  kArrowTurnRightTurnLeft,
  kArrowUTurnRight,
  kArrowUTurnLeft,
  kUnknown,
};

/// Maps TrafficControlDeviceType enums to string representations.
std::unordered_map<TrafficControlDeviceType, const char*, maliput::common::DefaultHash>
TrafficControlDeviceTypeMapper();

}  // namespace api
}  // namespace maliput

namespace std {

/// Specialization of std::hash for maliput::api::TrafficControlDeviceType.
template <>
struct hash<maliput::api::TrafficControlDeviceType> : public maliput::common::DefaultHash {};

}  // namespace std
