#!/bin/bash

# @file prereqs
# This file allows to install prerequisites that cannot be handled via `rosdep`
# (@see http://wiki.ros.org/rosdep for further reference). In particular,
# `libpython3-dev` is available in `ubuntu:bionic` but not for `rosdep` which
# is why it is provided via this script. See the following link:
# https://github.com/ros/rosdistro/blob/48e5975c756582415c50c06bd5ee0f61d780c21d/rosdep/python.yaml#L373-L395

set -e pipefail

source prereqs.lib

prereqs.init 'The maliput_py source distribution prerequisite setup script'

if prereqs.tag_applies "default|all"; then
    prereqs.assert_sudo

    prereqs.apt install --no-install-recommends libpython3-dev
fi

prereqs.done
