#!/bin/bash

# @file prereqs
# This file allows to install prerequisites that cannot be handled via `rosdep`
# (@see http://wiki.ros.org/rosdep for further reference). In particular,
# `libpython3-dev` is available in `rosdep` but not for `ubuntu:bionic` which
# is why it is provided via this script.

set -e pipefail

source prereqs.lib

prereqs.init 'The Maliput source distribution prerequisite setup script'

if prereqs.tag_applies "default|all"; then
    prereqs.assert_sudo

    prereqs.apt install --no-install-recommends libpython3-dev
fi

prereqs.done
