#!/bin/bash

set -e pipefail

source prereqs.lib

prereqs.init 'The Maliput source distribution prerequisite setup script'

if prereqs.tag_applies "default|all"; then
    prereqs.assert_sudo

    prereqs.apt install --no-install-recommends libpython3-dev
fi

prereqs.done
