#!/bin/bash

set -eo pipefail

# Install basic dependencies to checkout.
sudo apt-get update
sudo apt-get install -y --no-install-recommends awscli git

# We need ssh keys from TRI to access all private repos. Code below fetches them
# from an S3 bucket that TRI has, and is a bash version of the code located
# at: https://github.com/RobotLocomotion/drake-ci/blob/master/driver/configurations/aws.cmake
# and: https://github.com/RobotLocomotion/drake-ci/blob/master/tools/git_ssh.bash.in

SSH_IDENTITY_FILE=$( mktemp /tmp/id_rsa_XXXXXXXX )
aws s3 cp s3://drake-provisioning/id_rsa "$SSH_IDENTITY_FILE"
SSH_IDENTITY_SHA1=$( sha1sum "$SSH_IDENTITY_FILE" | cut -d' ' -f1 )
test "$SSH_IDENTITY_SHA1" = "8de7f79df9eb18344cf0e030d2ae3b658d81263b"
chmod 0400 "$SSH_IDENTITY_FILE"
GIT_SSH_FILE=$( mktemp /tmp/git_ssh_XXXXXXXX )
cat > $GIT_SSH_FILE <<EOF
ssh -i "$SSH_IDENTITY_FILE" -o StrictHostKeyChecking=no "\$@"
EOF
chmod 0755 $GIT_SSH_FILE
export GIT_SSH=$GIT_SSH_FILE

git clone git@github.com:ToyotaResearchInstitute/dsim-repos-index.git index

unset GIT_SSH
rm -f "$GIT_SSH_FILE"
rm -f "$SSH_IDENTITY_FILE"

if [ "$CHANGE_BRANCH" != "" ]; then
    echo "**** Merging custom branch $CHANGE_BRANCH into default branch ****"
    git -C index branch -q -f "$CHANGE_BRANCH" --track "remotes/origin/$CHANGE_BRANCH" 2>/dev/null || true
    git -C index merge -q --no-edit "$CHANGE_BRANCH" 2>/dev/null || true
    [ -z "$(git -C index diff)" ] || exit 1
else
    echo "**** Using default branch ****"
fi
