// BSD 3-Clause License
//
// Copyright (c) 2022-2026, Woven by Toyota. All rights reserved.
//
// Redistribution and use in source and binary forms, with or without
// modification, are permitted provided that the following conditions are met:
//
// * Redistributions of source code must retain the above copyright notice, this
//   list of conditions and the following disclaimer.
//
// * Redistributions in binary form must reproduce the above copyright notice,
//   this list of conditions and the following disclaimer in the documentation
//   and/or other materials provided with the distribution.
//
// * Neither the name of the copyright holder nor the names of its
//   contributors may be used to endorse or promote products derived from
//   this software without specific prior written permission.
//
// THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
// AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
// IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
// DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE
// FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
// DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
// SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
// CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
// OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
// OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
#include "maliput/api/rules/traffic_sign.h"

#include <cstddef>
#include <utility>
#include <vector>

namespace maliput {
namespace api {
namespace rules {

std::unordered_map<TrafficSignType, const char*, maliput::common::DefaultHash> TrafficSignTypeMapper() {
  constexpr std::size_t kTrafficSignTypeCount = static_cast<std::size_t>(TrafficSignType::kUnknown) + 1;
  const std::vector<const char*> kTypeNames{
      "None",
      "Other",
      "Stop",
      "Yield",
      "SpeedLimit",
      "NoEntry",
      "OneWay",
      "PedestrianCrossing",
      "NoLeftTurn",
      "NoRightTurn",
      "NoUTurn",
      "SchoolZone",
      "Construction",
      "RailroadCrossing",
      "NoOvertaking",
      "AllWay",
      "NoUTurnLeft",
      "NoUTurnRight",
      "StopLine",
      "Crosswalk",
      "DangerSpot",
      "ZebraCrossing",
      "Flight",
      "Cattle",
      "HorseRiders",
      "Amphibians",
      "FallingRocks",
      "SnowOrIce",
      "LooseGravel",
      "Waterside",
      "Clearance",
      "MovableBridge",
      "RightBeforeLeftNextIntersection",
      "TurnLeft",
      "TurnRight",
      "DoubleTurnLeft",
      "DoubleTurnRight",
      "HillDownwards",
      "HillUpwards",
      "UnevenRoad",
      "RoadSlipperyWetOrDirty",
      "SideWinds",
      "RoadNarrowing",
      "RoadNarrowingRight",
      "RoadNarrowingLeft",
      "RoadWorks",
      "TrafficQueues",
      "TwoWayTraffic",
      "AttentionTrafficLight",
      "Pedestrians",
      "ChildrenCrossing",
      "CycleRoute",
      "DeerCrossing",
      "UngatedLevelCrossing",
      "LevelCrossingMarker",
      "RailwayTrafficPriority",
      "GiveWay",
      "PriorityToOppositeDirection",
      "PriorityToOppositeDirectionUpsideDown",
      "PrescribedLeftTurn",
      "PrescribedRightTurn",
      "PrescribedStraight",
      "PrescribedRightWay",
      "PrescribedLeftWay",
      "PrescribedRightTurnAndStraight",
      "PrescribedLeftTurnAndStraight",
      "PrescribedLeftTurnAndRightTurn",
      "PrescribedLeftTurnRightTurnAndStraight",
      "Roundabout",
      "OnewayLeft",
      "OnewayRight",
      "PassLeft",
      "PassRight",
      "SideLaneOpenForTraffic",
      "SideLaneClosedForTraffic",
      "SideLaneClosingForTraffic",
      "BusStop",
      "TaxiStand",
      "BicyclesOnly",
      "HorseRidersOnly",
      "PedestriansOnly",
      "BicyclesPedestriansSharedOnly",
      "BicyclesPedestriansSeparatedLeftOnly",
      "BicyclesPedestriansSeparatedRightOnly",
      "PedestrianZoneBegin",
      "PedestrianZoneEnd",
      "BicycleRoadBegin",
      "BicycleRoadEnd",
      "BusLane",
      "BusLaneBegin",
      "BusLaneEnd",
      "AllProhibited",
      "MotorizedMultitrackProhibited",
      "TrucksProhibited",
      "BicyclesProhibited",
      "MotorcyclesProhibited",
      "MopedsProhibited",
      "HorseRidersProhibited",
      "HorseCarriagesProhibited",
      "CattleProhibited",
      "BusesProhibited",
      "CarsProhibited",
      "CarsTrailersProhibited",
      "TrucksTrailersProhibited",
      "TractorsProhibited",
      "PedestriansProhibited",
      "MotorVehiclesProhibited",
      "HazardousGoodsVehiclesProhibited",
      "OverWeightVehiclesProhibited",
      "VehiclesAxleOverWeightProhibited",
      "VehiclesExcessWidthProhibited",
      "VehiclesExcessHeightProhibited",
      "VehiclesExcessLengthProhibited",
      "DoNotEnter",
      "SnowChainsRequired",
      "WaterPollutantVehiclesProhibited",
      "EnvironmentalZoneBegin",
      "EnvironmentalZoneEnd",
      "PrescribedUTurnLeft",
      "PrescribedUTurnRight",
      "MinimumDistanceForTrucks",
      "SpeedLimitBegin",
      "SpeedLimitZoneBegin",
      "SpeedLimitZoneEnd",
      "MinimumSpeedBegin",
      "OvertakingBanBegin",
      "OvertakingBanForTrucksBegin",
      "SpeedLimitEnd",
      "MinimumSpeedEnd",
      "OvertakingBanEnd",
      "OvertakingBanForTrucksEnd",
      "AllRestrictionsEnd",
      "NoStopping",
      "NoParking",
      "NoParkingZoneBegin",
      "NoParkingZoneEnd",
      "RightOfWayNextIntersection",
      "RightOfWayBegin",
      "RightOfWayEnd",
      "PriorityOverOppositeDirection",
      "PriorityOverOppositeDirectionUpsideDown",
      "TownBegin",
      "TownEnd",
      "CarParking",
      "CarParkingZoneBegin",
      "CarParkingZoneEnd",
      "SidewalkHalfParkingLeft",
      "SidewalkHalfParkingRight",
      "SidewalkParkingLeft",
      "SidewalkParkingRight",
      "SidewalkPerpendicularHalfParkingLeft",
      "SidewalkPerpendicularHalfParkingRight",
      "SidewalkPerpendicularParkingLeft",
      "SidewalkPerpendicularParkingRight",
      "LivingStreetBegin",
      "LivingStreetEnd",
      "Tunnel",
      "EmergencyStoppingLeft",
      "EmergencyStoppingRight",
      "HighwayBegin",
      "HighwayEnd",
      "ExpresswayBegin",
      "ExpresswayEnd",
      "NamedHighwayExit",
      "NamedExpresswayExit",
      "NamedRoadExit",
      "HighwayExit",
      "ExpresswayExit",
      "OnewayStreet",
      "CrossingGuards",
      "Deadend",
      "DeadendExcludingDesignatedActors",
      "FirstAidStation",
      "PoliceStation",
      "Telephone",
      "FillingStation",
      "Hotel",
      "Inn",
      "Kiosk",
      "Toilet",
      "Chapel",
      "TouristInfo",
      "RepairService",
      "PedestrianUnderpass",
      "PedestrianBridge",
      "CamperPlace",
      "AdvisorySpeedLimitBegin",
      "AdvisorySpeedLimitEnd",
      "PlaceName",
      "TouristAttraction",
      "TouristRoute",
      "TouristArea",
      "ShoulderNotPassableMotorVehicles",
      "ShoulderUnsafeTrucksTractors",
      "TollBegin",
      "TollEnd",
      "TollRoad",
      "Customs",
      "InternationalBorderInfo",
      "StreetlightRedBand",
      "FederalHighwayRouteNumber",
      "HighwayRouteNumber",
      "HighwayInterchangeNumber",
      "EuropeanRouteNumber",
      "FederalHighwayDirectionLeft",
      "FederalHighwayDirectionRight",
      "PrimaryRoadDirectionLeft",
      "PrimaryRoadDirectionRight",
      "SecondaryRoadDirectionLeft",
      "SecondaryRoadDirectionRight",
      "DirectionDesignatedActorsLeft",
      "DirectionDesignatedActorsRight",
      "RoutingDesignatedActors",
      "DirectionToHighwayLeft",
      "DirectionToHighwayRight",
      "DirectionToLocalDestinationLeft",
      "DirectionToLocalDestinationRight",
      "ConsolidatedDirections",
      "StreetName",
      "DirectionPreannouncement",
      "DirectionPreannouncementLaneConfig",
      "DirectionPreannouncementHighwayEntries",
      "HighwayAnnouncement",
      "OtherRoadAnnouncement",
      "HighwayAnnouncementTruckStop",
      "HighwayPreannouncementDirections",
      "PoleExit",
      "HighwayDistanceBoard",
      "DetourLeft",
      "DetourRight",
      "NumberedDetour",
      "DetourBegin",
      "DetourEnd",
      "DetourRoutingBoard",
      "OptionalDetour",
      "OptionalDetourRouting",
      "RouteRecommendation",
      "RouteRecommendationEnd",
      "AnnounceLaneTransitionLeft",
      "AnnounceLaneTransitionRight",
      "AnnounceRightLaneEnd",
      "AnnounceLeftLaneEnd",
      "AnnounceRightLaneBegin",
      "AnnounceLeftLaneBegin",
      "AnnounceLaneConsolidation",
      "DetourCityBlock",
      "Gate",
      "PoleWarning",
      "TrafficCone",
      "MobileLaneClosure",
      "ReflectorPost",
      "DirectionalBoardWarning",
      "GuidingPlate",
      "GuidingPlateWedges",
      "ParkingHazard",
      "TrafficLightGreenArrow",
      "Text",
      "Space",
      "Time",
      "Arrow",
      "ConstrainedTo",
      "Except",
      "ValidForDistance",
      "PriorityRoadBottomLeftFourWay",
      "PriorityRoadTopLeftFourWay",
      "PriorityRoadBottomLeftThreeWayStraight",
      "PriorityRoadBottomLeftThreeWaySideways",
      "PriorityRoadTopLeftThreeWayStraight",
      "PriorityRoadBottomRightFourWay",
      "PriorityRoadTopRightFourWay",
      "PriorityRoadBottomRightThreeWayStraight",
      "PriorityRoadBottomRightThreeWaySideway",
      "PriorityRoadTopRightThreeWayStraight",
      "ValidInDistance",
      "StopIn",
      "LeftArrow",
      "LeftBendArrow",
      "RightArrow",
      "RightBendArrow",
      "Accident",
      "Snow",
      "Fog",
      "RollingHighwayInformation",
      "Services",
      "TimeRange",
      "ParkingDiscTimeRestriction",
      "Weight",
      "Wet",
      "ParkingConstraint",
      "NoWaitingSideStripes",
      "Rain",
      "SnowRain",
      "Night",
      "Stop4Way",
      "Truck",
      "TractorsMayBePassed",
      "Hazardous",
      "Trailer",
      "Zone",
      "Motorcycle",
      "MotorcycleAllowed",
      "Car",
      "Unknown",
  };
  MALIPUT_THROW_UNLESS(kTypeNames.size() == kTrafficSignTypeCount);
  std::unordered_map<TrafficSignType, const char*, maliput::common::DefaultHash> result;
  result.reserve(kTypeNames.size());
  for (std::size_t i = 0; i < kTypeNames.size(); ++i) {
    result.emplace(static_cast<TrafficSignType>(i), kTypeNames[i]);
  }
  return result;
}

std::unordered_map<TrafficSignValueUnit, const char*, maliput::common::DefaultHash> TrafficSignValueUnitMapper() {
  std::unordered_map<TrafficSignValueUnit, const char*, maliput::common::DefaultHash> result;
  result.emplace(TrafficSignValueUnit::kMetersPerSecond, "m/s");
  result.emplace(TrafficSignValueUnit::kKilometersPerHour, "km/h");
  result.emplace(TrafficSignValueUnit::kMilesPerHour, "mph");
  result.emplace(TrafficSignValueUnit::kMeters, "m");
  result.emplace(TrafficSignValueUnit::kKilometers, "km");
  result.emplace(TrafficSignValueUnit::kFeet, "ft");
  result.emplace(TrafficSignValueUnit::kMiles, "mile");
  result.emplace(TrafficSignValueUnit::kPercent, "%");
  result.emplace(TrafficSignValueUnit::kKilograms, "kg");
  result.emplace(TrafficSignValueUnit::kMetricTons, "t");
  return result;
}

TrafficSign::TrafficSign(const Id& id, const TrafficSignType& type, const InertialPosition& position_road_network,
                         const Rotation& orientation_road_network, const std::optional<std::string>& message,
                         std::vector<LaneId> related_lanes, std::vector<Id> dependent_signs,
                         const maliput::math::BoundingBox& bounding_box, const std::optional<TrafficSignValue>& value,
                         std::unordered_map<std::string, std::string> properties, bool is_dynamic, bool is_movable)
    : id_(id),
      type_(type),
      position_road_network_(position_road_network),
      orientation_road_network_(orientation_road_network),
      message_(message),
      related_lanes_(std::move(related_lanes)),
      dependent_signs_(std::move(dependent_signs)),
      bounding_box_(bounding_box),
      value_(value),
      properties_(std::move(properties)),
      is_dynamic_(is_dynamic),
      is_movable_(is_movable) {}

}  // namespace rules
}  // namespace api
}  // namespace maliput
