# Util script to make the changes necessary for a new release.
# Usage: ./bump_version.sh <old_version> <new_version>
# Example: ./bump_version.sh 0.10.0 0.11.0

# Bump version number
OLD_VERSION=$1
NEW_VERSION=$2

if [ -z "$OLD_VERSION" ] || [ -z "$NEW_VERSION" ]; then
  echo "Usage: $0 <old_version> <new_version>"
  exit 1
fi

# Find and replace version in all relevant files: MODULE.bazel, package.xml, CMakeLists.txt
find . -type f \( -name "MODULE.bazel" -o -name "package.xml" -o -name "CMakeLists.txt" \) -exec sed -i "s/$OLD_VERSION/$NEW_VERSION/g" {} +
echo "Version bumped from $OLD_VERSION to $NEW_VERSION in all relevant files."

# Generate changelog with catkin tools
catkin_generate_changelog

# Replace the "Forthcoming" string with the new version in CHANGELOG.rst and add the date in the format (YYYY-MM-DD)
sed -i "s/Forthcoming/$NEW_VERSION ($(date +%Y-%m-%d))/g" CHANGELOG.rst
echo "Changelog updated with new version $NEW_VERSION."

# Smaller fixes
# Make the autogenerated dash line (-----------) have the same length as the others (-------------------)
sed -i 's/^-----------$/-------------------/' CHANGELOG.rst
echo "Dash lines in CHANGELOG.rst adjusted for consistency."

# Remove sub-bullets from the new version entry in CHANGELOG.rst without changing the older entries
awk '
/^---+$/ {
  dash_count++
  print
  next
}
{
  # Remove indented bullets only in the newest version section
  if (dash_count == 1 && /^[[:space:]]+\* /)
    next

  # Also remove indented dashed separators in newest section
  if (dash_count == 1 && /^[[:space:]]+---+/)
    next

  print
}
' CHANGELOG.rst > CHANGELOG.tmp && mv CHANGELOG.tmp CHANGELOG.rst
echo "Sub-bullets removed from the new version entry in CHANGELOG.rst."
