if ("${CMAKE_CXX_COMPILER_ID} " MATCHES "Clang ")
  # Address Sanitizer Configuration
  option(ADDRESS_SANITIZER "Enable Clang Address Sanitizer" OFF)
  if (ADDRESS_SANITIZER)
      message(STATUS "Address Sanitizer - enabled")
      set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -g -fsanitize=address -fno-optimize-sibling-calls -fsanitize-address-use-after-scope")
      set(LDFLAGS "${LDFLAGS} -fsanitize=address -fno-optimize-sibling-calls -fsanitize-address-use-after-scope")
      set(SANITIZERS on)
  else()
      message(STATUS "Address Sanitizer - disabled")
  endif()
else ()
    message(STATUS "Compiler Id:${CMAKE_CXX_COMPILER_ID} - Sanitizers disabled.")
endif ()
