# Cuts a github release with a stable release archive [1] from a *.*.* tag.
#
# [1] See https://blog.bazel.build/2023/02/15/github-archive-checksum.html
# for why source code assets are not stable).
name: Release

on:
  push:
    tags:
      - "*.*.*"

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set Variables
        shell: bash
        run: echo "ARCHIVE_NAME=${{ github.event.repository.name }}-${GITHUB_REF_NAME}" >> $GITHUB_ENV
      - name: Variables
        run: |
          echo "Repository Name: ${{ github.event.repository.name }}"
          echo "GITHUB_REF: ${GITHUB_REF}"
          echo "GITUB_REF_NAME: ${GITHUB_REF_NAME}"
          echo "ARCHIVE_NAME: ${{ env.ARCHIVE_NAME }}"
      - name: Create Release Asset
        shell: bash
        run: git archive $GITHUB_REF --prefix=${{ env.ARCHIVE_NAME }}/ -o "${{ env.ARCHIVE_NAME }}.tar.gz"
      - name: Cut a Release
        uses: softprops/action-gh-release@v2
        with:
          draft: false
          prerelease: false
          files: ${{ env.ARCHIVE_NAME }}.tar.gz
